### ISSUE TITLE
Angular SSR

### ISSUE THREAD

**Issue by jasonc624** [omnedia/ngx-marquee#1]
I've noticed this components fails in angular SSR since they make use of intersectionObserver. I had to do check like so. Might save some head scratches if it was done in the lib itself.

  readonly platformId: Object = inject(PLATFORM_ID);
  _isBrowser: boolean = isPlatformBrowser(this.platformId);

**Comment by xSentry** [comment]
I havent worked with SSR till now. Thanks for the info.
I'll have to look into some alternatives to support SSR but that would take a bit of time.
If you need it faster and have a working solution in mind, feel free to fork the repo and create a PR. I'll test and merge it then.

**Comment by xSentry** [comment]
Fixed in Release 1.1.1
