### ISSUE TITLE
Support for Angular 19

### ISSUE THREAD

**Issue by danailov-z** [omnedia/ngx-marquee#2]
Hello, any plans on supporting angular 19 soon.

This is what I get, when trying to install it Angular 19 project:

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: appp@0.0.0
npm error Found: @angular/common@19.0.3
npm error node_modules/@angular/common
npm error   @angular/common@"^19.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @angular/common@"^18.2.0" from @omnedia/ngx-marquee@1.1.1
npm error node_modules/@omnedia/ngx-marquee
npm error   @omnedia/ngx-marquee@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see: ....

Thanks in advance

**Comment by xSentry** [comment]
Hey, as soon as I find some time I'll add support for 19.* this week.

**Comment by xSentry** [comment]
Updated with commit [24395a4](https://github.com/omnedia/ngx-marquee/commit/24395a426d86d18d80107af5f10e69e0be5692bb) and release [2.0.0](https://github.com/omnedia/ngx-marquee/releases/tag/2.0.0)
