### ISSUE TITLE
Change detection issue

### ISSUE THREAD

**Issue by auloma04** [omnedia/ngx-marquee#3]
Hi everyone.

I am using this component to display products card. Each product card displays fixed datas but also asynchronous data.

My problem is that this async data is never displayed in the marquee component. Initial values are still displayed even if console.log I placed in effects display the right values.  
I placed the same components outside the marquee, to compare. They are displaying the right datas. 

I looked into the source code and it seems logic. But I think I am not the only one to get in this kind of trouble.

I am using the 1.1.1 version with an Angular 18 app.

Thank you

**Comment by xSentry** [comment]
The component works through grabbing the content inside the `<om-marquee>` tags that are tagged with the `#OmMarqueeContent` id and builds the marquee with them.
It is monitoring changes of the dom through this.
```ts
this.elementRefs?.changes.pipe(takeUntil(this.destroy$)).subscribe(() => {
      this.getMarqueeContent();
});
```

My guess is, that the changes arent detected correctly or the Change Detection isnt triggered.
Do you perhaps have a repository or a project that you could share with me?
Maybe just the component code?
I would try debugging the issue with that.

**Comment by auloma04** [comment]
Thank you for your answer.

I guess elementRefs.changes only emits when a ref is added or removed.

Here is a minimal reproducing project for my issue: https://stackblitz.com/edit/stackblitz-starters-aj1kmidr?file=src%2Fmain.ts
In this case, the problem happens with asynchronous data. But in my initial case, the problem also happens with an Angular mat-checkbox, which is supposed to be checked by default, but in the marquee it is not checked.

Thank you for your help

**Comment by xSentry** [comment]
I updated the library.
Version `2.1.0` is the fix for Angular v19.
Version `1.2.0` the same but for Angular v18.

**Comment by auloma04** [comment]
Perfect, thanks. Happy for having contributed :)
Regards
